#!/bin/bash

# defaults write com.apple.finder AppleShowAllFiles YES

: ${1:?"USAGE: ./hidden_files [true/false]"}

if [ "$1" == "true" ]; then
  defaults write com.apple.finder AppleShowAllFiles YES
elif [ "$1" == "false" ]; then
  defaults write com.apple.finder AppleShowAllFiles NO
fi

killall Finder