#!/bin/bash

function usage {
  echo "find_str [PATH] [FILE_PATTERN] [SEARCH_STRING]"
  echo "find_str code/ \"*.c\" \"some_function()\""
}

if [ -n "$1" ] && [ -n "$2" ] && [ -n "$3" ]; then
  echo "Looking in \"$1\" for $2 files containing $3"
  find "$1" -name "$2" -type f | xargs grep "$3" --color=always
else  
  usage
fi
